version: 2

models:
  - name: i_gpm_e_adr
    tags: ["interface"]
    description: >
      Table d'interface. Utilisée uniquement pour pallier à une enventuelle absence (complète ou partielle) de la table 'gpm_e_adr' de la base de données source.

  - name: i_gpm_n_fact
    tags: ["interface"]
    description: >
      Table d'interface. Utilisée uniquement pour pallier à une enventuelle absence (complète ou partielle) de la table 'gpm_n_fact' de la base de données source.