version: 2

models:
  - name: fact_h_remun
    config:
      tags:
        - direction_generale
        - mart_direction_generale
    description: >
      Cumulatif des heures travaillées, des heures supplémentaires et des heures d'absences par date de chèque, matricule, code de paiement (avec le profiler).
    # tests:
    #   - core_dashboards_store.resolution:
    #       combination_of_columns:
    #         - matr
    #         - no_seq
    #         - corp_empl
    #         - date_cheq
    #         - code_pmnt