version: 2

models:
  - name: car_tp_procure
    config:
      tags:
        - rf
      schema: "rf_staging"
    description: >
      Table de fait qui fournit l'historique du solde 
    tests:
      - core_dashboards_store.resolution:
          combination_of_columns:
            - code_perm
            - fiche
            - annee
            - eco