version: 2

models:
  - name: utilisateurs_gestionnaires
    config:
      tags:
        - suivi_etc
        - rls
      schema: rls
    description: >
      Table utilisée uniquement pour avoir les gestionnaire des unités de service.
    tests: 
      - core_dashboard_store.resolution: 
          combination_of_columns: 
            - compte_authentification
            - Ecole
    columns:
      - name: compte_authentification
        tests: 
            - not_null
      - name: Ecole
        tests: 
            - not_null            
  - name: lieux_travail
    config:
      tags:
        - suivi_etc
        - rls
      schema: rls
    description: >
      Table utilisée uniquement pour avoir la liste des codes d'écoles et leur nom.
    tests: 
      - core_dashboard_store.resolution: 
          combination_of_columns: 
            - lieu_trav
    columns:
      - name: lieu_trav
        tests: 
            - not_null
      - name: lieu_trav_desc
        tests: 
            - not_null   
