version: 2

models:
  - name: i_sdg_e_dan
    tags: 
      - interface
      - rf
    description: >
      Table d'interface. Utilisée uniquement pour pallier à une enventuelle absence (complète ou partielle) de la table 'sdg_e_dan' de la base de données source.
      
  - name: i_sdg_e_cumul_dan
    tags: 
      - interface
      - rf
    description: >
      Table d'interface. Utilisée uniquement pour pallier à une enventuelle absence (complète ou partielle) de la table 'sdg_e_dan' de la base de données source.