version: 2

models:
  - name: fact_h_remun
    config:
      tags:
        - human_resources
        - mart_human_resources
        - suivi_etc
    description: >
      Cumulatif des heures travaillées, des heures supplémentaires et des heures d'absences par date de chèque, matricule, code de paiement (avec le profiler).
    tests:
      - core_dashboards_store.resolution:
          combination_of_columns:
            - an_budg
            - no_per
            - gr_paie
            - matr
            - corp_emploi
            - stat_eng
            - sect
            - aff
            - typeremun
            - mode
            - lieu_trav
            - no_seq
            - code_pmnt