version: 2

models:
  - name: i_pai_habs
    tags: ["interface"]
    description: >
      Table d'interface. Utilisée uniquement pour pallier à une enventuelle absence (complète ou partielle) de la table 'i_paie_hemp' de la base de données source.
