version: 2

seeds:
  - name: pmnt_zero_keep
    description: contient les codes de paiement que le CSS souhaite considérer malgré un montant nul lors du calcul des ETC
    config:
      tags: 
        - human_resources
        - suivi_etc
      schema: human_resources_seeds
      column_types:
        code_pmnt: nvarchar(6)
        descr: nvarchar(50)
    columns:
      - name: code_pmnt
        description: code de paiement
        tests:
          - not_null
          - unique    
      - name: descr
        description: descriptif
        tests:
          - not_null


  - name: ens_qualification
    description: >
      Une table qui vient spécifier si les diplômes, certifications, brevets etc des enseignants font d'eux des enseignants légalement qualifiés ou non.
    columns:
      - name: code
        description: Représentation codifiée des papiers
        tests:
          - not_null
          - unique  # Si les codes sont censés être uniques
      - name: descr
        description: Description des papiers
        tests:
          - not_null
      - name: is_qualified
        description: Légalement qualifié ou non ?
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]  # Pour assurer que les valeurs sont 0 ou 1
    config:
      tags:
        - human_resources
      schema: human_resources_seeds
      column_types:
        code: nvarchar(3)
        descr: nvarchar(255)
        is_qualified: bit

  - name: statut_enseignant
    description: >
      Une table qui spécifie les statuts d'engagement des enseignant(e)s.
    columns:
      - name: code
        description: Représentation codifiée des statuts d'engagement
        tests:
          - not_null
          - unique  # Assure que les codes sont uniques
      - name: statut
        description: Description des statuts d'engagement
        tests:
          - not_null
    config:
      tags:
        - human_resources
      schema: human_resources_seeds
      column_types:
        code: nvarchar(3)
        statut: nvarchar(64)

  - name: secteur
    description: >
      Une table contenant les informations sur les secteurs des écoles et leurs caractéristiques.
    columns:
      - name: ua_Id
        description: L'ID de l'école
        tests:
          - not_null
      - name: secteur_Id
        description: L'ID du secteur
        tests:
          - not_null
      - name: secteur_Descr
        description: Description du secteur
        tests:
          - not_null
      - name: ordre_Ens
        description: Ordre des enseignants dans ce secteur
        tests:
          - not_null
    config:
      tags:
        - human_resources
      schema: human_resources_seeds
      column_types:
        ua_Id: int
        secteur_Id: int
        secteur_Descr: nvarchar(32) 
        ordre_Ens: nvarchar(3)


