version: 2

seeds:
  - name: pmnt_zero_keep
    description: contient les codes de paiement que le CSS souhaite considérer malgré un montant nul lors du calcul des ETC
    config:
      tags: 
        - human_resources
        - suivi_etc
      schema: human_resources_seeds
      column_types:
        code_pmnt: nvarchar(6)
        descr: nvarchar(50)
    columns:
      - name: code_pmnt
        description: code de paiement
        tests:
          - not_null
          - unique    
      - name: descr
        description: descriptif
        tests:
          - not_null




