version: 2

models:
  - name: i_fin_nomen_unit_adm
    tags: ["interface"]
    description: >
      Table d'interface. Utilisée uniquement pour pallier à une enventuelle absence (complète ou partielle) de la table 'fin_nomen_unit_adm' de la base de données source.