version: 2

models:
  - name: i_e_ele_adultes
    tags: 
      - interface
      - educ_serv_adultes
      - populations_adultes
    description: >
      Table d'interface. Utilisée uniquement pour pallier de la table 'E_Ele' la base de données source.
  - name: i_e_freq_adultes
    tags: 
      - interface
      - educ_serv_adultes
      - populations_adultes
    description: >
      Table d'interface. Utilisée uniquement pour pallier la table 'i_e_freq_adultes' de la base de données source.
  - name: i_t_prog_adultes
    tags: 
      - interface
      - educ_serv_adultes
      - populations_adultes
    description: >
      Table d'interface. Utilisée uniquement pour pallier la table 'T_Prog' de la base de données source.
  - name: i_t_wl_descr_adultes
    tags: 
      - interface
      - educ_serv_adultes
      - populations_adultes
    description: >
      Table d'interface. Utilisée uniquement pour pallier la table 'WL_Descr' de la base de données source.
  - name: i_t_ecocen_adultes
    tags: 
      - interface
      - educ_serv_adultes
      - populations_adultes
    description: >
      Table d'interface. Utilisée uniquement pour pallier la table 'E_RI_Resultats' de la base de données source.
  - name: i_t_motif_adultes
    tags: 
      - interface
      - educ_serv_adultes
      - populations_adultes
    description: >
      Table d'interface. Utilisée uniquement pour pallier la table 'T_motif' de la base de données source.
  - name: i_e_o_orghor_adultes
    tags: 
      - interface
      - educ_serv_adultes
      - populations_adultes
    description: >
      Table d'interface. Utilisée uniquement pour pallier la table 'o_orghor' de la base de données source.