version: 2

models:
  - name: cdpvd_stg_dim_absences_inclusion
    tags: ["absenteeism"]
    description: >
      Table auxiliaire sélectionnant les raisons d'absences et de retards que vous souhaitez inclure dans le calcul.
    tests:
      - core_dashboards_store.resolution:
          combination_of_columns:
            - id_eco
            - motif_abs
    columns:
      - name: category_abs
        tests:
          - not_null
