version: 2

models:
  - name: stg_dist_cmpt
    config:
      tags:
        - human_resources
    description: >
      Table auxiliaire qui limite la table aux distributions de comptes budgétaires sur une période donnée.
    tests:
      - core_dashboards_store.resolution:
          combination_of_columns:
            - matr
            - no_cheq
            - no_seq
            - no_cmpt
  - name: stg_perim_hitorique_emplois
    config:
      tags:
        - human_resources
    description: >
      Table de staging pour identifier le perimètre utiliser dans la fact_h_remun
    tests:
      - core_dashboards_store.resolution:
          combination_of_columns:
            - matr
            - ref_empl
            - date_eff