version: 2

models:
  - name: fact_rrm_retention
    description: >
    config:
      tags:
        - rrm
        - human_resources
      schema: human_resources_features
    columns:
      - name: matr
        description: Matricule de l'employé
        tests:
          - not_null
      - name: corp_empl
        description: Code du corps d'emploi
        tests:
          - not_null          
      - name: lieu_trav
        description: Code du lieu de travail
        tests:
          - not_null
      - name: date_rrm
        description: Date d'embauche
        tests:
          - not_null
      - name: annee
        description: Annee de la date d'embauche
        tests:
          - not_null
      - name: mois
        description: Mois de la date d'embauche
        tests:
          - not_null
      - name: semaine
        description: Semaine de la date d'embauche
        tests:
          - not_null                                                    
  
  - name: fact_rrm_roulement
    description: >
    config:
      tags:
        - rrm
        - human_resources
      schema: human_resources_features
    columns:
      - name: matr
        description: Matricule de l'employé
        tests:
          - not_null
      - name: corp_empl
        description: Code du corps d'emploi
        tests:
          - not_null          
      - name: lieu_trav
        description: Code du lieu de travail
        tests:
          - not_null
      - name: date_rrm
        description: Date de démission
        tests:
          - not_null
      - name: annee
        description: Annee de la date de démission
        tests:
          - not_null
      - name: mois
        description: Mois de la date de démission
        tests:
          - not_null
      - name: semaine
        description: Semaine de la date de démission
        tests:
          - not_null
  
  - name: fact_rrm_mouvement
    description: >
    config:
      tags:
        - rrm
        - human_resources
      schema: human_resources_features
    columns:
      - name: matr
        description: Matricule de l'employé
        tests:
          - not_null
      - name: corp_empl
        description: Code du corps d'emploi
        tests:
          - not_null          
      - name: lieu_trav
        description: Code du lieu de travail
        tests:
          - not_null
      - name: date_rrm
        description: Date de la promotion
        tests:
          - not_null
      - name: annee
        description: Annee de la date de la promotion
        tests:
          - not_null
      - name: mois
        description: Mois de la date de la promotion
        tests:
          - not_null
      - name: semaine
        description: Semaine de la date de la promotion
        tests:
          - not_null
  
  - name: fact_rrm_consolide
    description: >
    config:
      tags:
        - rrm
        - human_resources
      schema: human_resources_features
    columns:
      - name: matr
        description: Matricule de l'employé
        tests:
          - not_null
      - name: corp_empl
        description: Code du corps d'emploi
        tests:
          - not_null          
      - name: lieu_trav
        description: Code du lieu de travail
        tests:
          - not_null
      - name: date_rrm
        description: Date RRM
        tests:
          - not_null
      - name: annee
        description: Annee de la date RRM
        tests:
          - not_null
      - name: mois
        description: Mois de la date RRM
        tests:
          - not_null
      - name: semaine
        description: Semaine de la date RRM
        tests:
          - not_null