version: 2

seeds:
  - name: secteur
    description: sdfdsf
    columns:
      - name: ua_Id
        description: L'ID de l'école
        tests:
          - not_null
      - name: secteur_Id
        description: The description of the etat_employe.
        tests:
          - not_null
      - name: secteur_Descr
        description: The description of the etat_employe.
        tests:
          - not_null          

    config:
      tags:
        - human_resources
      schema: human_resources_seeds
      column_types:
        ua_Id: int
        secteur_Id: int
        secteur_Descr: nvarchar(32)

  - name: type_absence
    description: Regroupement des motifs d'absence sous des catégories plus parlantes
    columns:
      - name: motif_id
        description: L'ID du motif
      - name: categories
        description: Catégories 
      - name: statut
        description: Statut

    config:
      tags:
        - human_resources
      schema: human_resources_seeds
      column_types:
        motif_id: nvarchar(2)
        categories: nvarchar(50)
        statut: bit

  - name: heures_travaillees
    description: Heures travaillées selon les catégories d'emplois
    columns:
      - name: cat_emploi
        description: Catégorie d'emploi
      - name: heures
        description: Heures travaillées par jour

    config:
      tags:
        - human_resources
      schema: human_resources_seeds
      column_types:
        cat_emploi: nvarchar(1)
        heures: float        